### ISSUE TITLE
Disable negative or positive mode search

### ISSUE THREAD

**Issue by a-indra** [Protea-Glycosciences/GlyCombo#7]
Hi Chris,
Thanks for this great tool! I've been trying it out today. I'm wondering about the rationale for forcing the inclusion of both [M-H] and [M+H] in the search. I can disable neutral [M] in the Advanced tab, but I'm unable to uncheck the positive mode feature. 

Is this by design, and the operator can simply filter out 'inappropriate' charges in the output file?

Thank you,
Anuk

**Comment by chrashwood** [comment]
Hi Anuk,

Thanks! We've forced the inclusion of M-H and M+H in the search when using mzML input because we automatically extract the polarity of the MS2 scan and calculate the neutral glycan mass based on that assumption. If there are no positive mode MS2 scans, GlyCombo won't identify any M+H adducted glycans, and the same for negative mode. Our rationale is that all adducts require this initial extraction of the MS2 scan polarity, and then we perform a mass offset depending on the selected adducts.

If this assumption or rationale doesn't work with your data, the text input option (as opposed to mzML input option) allows you to select whichever adducts you would like to interpret.

Thanks for using GlyCombo!

Cheers,
Chris

**Comment by a-indra** [comment]
Hi Chris, that makes sense. Thanks for the prompt reply and detailed explanation!
